"""corrigindo bug.

Revision ID: 19cd489c5520
Revises: 998313273a25
Create Date: 2026-09-05 19:22:38.070095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19cd489c5520'
down_revision: Union[str, Sequence[str], None] = '998313273a25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    """Upgrade schema."""
    pass
      
    

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
