"""adionando role

Revision ID: 5be232bb5dac
Revises: 4d363d2416b0
Create Date: 2026-09-09 23:27:56.784399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5be232bb5dac'
down_revision: Union[str, Sequence[str], None] = '4d363d2416b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('role', sa.String(), nullable=False))
    op.drop_column('usuarios', 'admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('usuarios', 'role')
    # ### end Alembic commands ###
