"""nova coluna -criado_em:

Revision ID: ee00120fce52
Revises: 064e5b91db0a
Create Date: 2026-09-05 14:29:50.400853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee00120fce52'
down_revision: Union[str, Sequence[str], None] = '064e5b91db0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        'usuarios',
        sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False)
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'criado_em')
    # ### end Alembic commands ###
